[package]
name = "crane_core"
version.workspace = true
edition.workspace = true

[dependencies]
nalgebra = { workspace = true, features = ["serde-serialize"] }
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
